from setuptools import setup, find_packages
setup(
    name='mri2ct',
    version='1.0.0',
    description='Hybrid Diffusion-GAN for MRI to CT Translation with Uncertainty Quantification',
    author='Your Name',
    author_email='your.email@example.com',
    url='https://github.com/yourusername/mri2ct',
    packages=find_packages(),
    install_requires=[
        'torch>=2.0.0',
        'torchvision>=0.15.0',
        'monai[all]>=1.3.0',
        'torchio>=0.19.0',
        'SimpleITK>=2.3.0',
        'antspyx>=0.4.0',
        'hydra-core>=1.3.0',
        'omegaconf>=2.3.0',
        'wandb>=0.15.0',
        'matplotlib>=3.7.0',
        'panel>=1.3.0',
        'gradio>=4.0.0',
        'scikit-learn>=1.3.0',
        'scikit-image>=0.21.0',
        'scipy>=1.11.0',
        'nibabel>=5.1.0',
        'pandas>=2.0.0',
        'tqdm>=4.65.0',
        'einops>=0.7.0',
        'timm>=0.9.0',
        'pillow>=10.0.0',
    ],
    python_requires='>=3.8',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Medical Science Apps.',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    entry_points={
        'console_scripts': [
            'mri2ct-train-diffusion=train_diffusion:main',
            'mri2ct-train-refiner=train_refiner:main',
            'mri2ct-infer=infer_sct:main',
            'mri2ct-gui=interface.gui_app:main',
        ],
    },
)
